# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/300counter
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #切换数据源为数据池druid
    type: com.alibaba.druid.pool.DruidDataSource
    #druid配置
    initialSize: 5
    minIdle: 10
    maxActive: 20
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 2000
    minEvictableIdleTimeMillis: 600000
    maxEvictableIdleTimeMillis: 900000
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3200
    jedis:
      pool:
        max-idle: 10
        min-idle: 3
        max-active: 20
        max-wait: 10000
server:
  port: 8081
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl